#pragma once

#define BANK_SELECT 0
#define MODULATION 1
#define BREATH_CONTROLLER 2
#define CC_DEACTIVATED 3
#define FOOT_CONTROLLER 4
#define PORTAMENTO_TIME 5
#define DATA_ENTRY_MSB 6
#define VOLUME 7
#define BALENCE 8
#define PAN 10
#define EXPRESSION 11
#define EFFECT_CONTROLLER_1 12
#define EFFECT_CONTROLLER_2 13
